spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1015

  jpa:
    hibernate:
      ddl-auto: update    # 更新或创建数据表结构
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true    # 控制台打印sql语句