spring:
  application:
    name: consumer-consumer

server:
  port: 8200

eureka:
  instance:
    prefer-ip-address: true   # \u6CE8\u518C\u670D\u52A1\u7684\u65F6\u5019\u4F7F\u7528\u670D\u52A1\u7684ip\u5730\u5740
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka