spring:
  datasource:
    username: root
    password: 1015
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eesy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    type: com.mchange.v2.c3p0.ComboPooledDataSource

mybatis:
  type-aliases-package: com.cyy.springboot.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml